#!/usr/bin/env python
import os
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
import cv2 as cv

# Subscription topic
topic = "/pepper_robot/camera/front/camera/image_raw"

class ImageRetriever:

  def __init__(self, topic):
    # CvBridge Object to convert Sensor_msgs Image to cv2 Image
    self.bridge = CvBridge()
    self.topic = topic
    # Subscription as a Subscriber to the topic /pepper_robot/camera/front/camera/image_raw 
    rospy.loginfo("Intialized Subcriber to topic %s", self.topic) 
    self.image_sub = rospy.Subscriber(topic, Image, self.callback)

  def callback(self, data):
    try:
      # Conversion to cv2 image using bgr8 encoding 
      frame = self.bridge.imgmsg_to_cv2(data, "bgr8")
    except CvBridgeError as e:
      print(e)
    # Showing frame    
    cv.imshow("Camera_Stream", frame)

if __name__ == '__main__':
  # Rospy Node
  rospy.init_node("camera_stream")
  rospy.loginfo("Intializing /camera_stream node")
  ir = ImageRetriever(topic)
  try:
      rospy.spin()
  except KeyboardInterrupt:
      print("Shutting down")
  cv.destroyAllWindows()