#!/usr/bin/env python
# -------------------------------------------------------------------
# *
# * This module has been developed by Group 18 @ Cognitive Robotics DIEM.UNISA.
# *
# * Title:	detector_node
# * Author:	Fina, Puzo, Russomanno, Ventre
# * Org.: 	UNISA - DIEM - Artificial Intelligence - Cognitive Robotics - Group 18
# * Date:    23 Nov, 2020
# *
# * This file implements a ROS node able to capture an image when the robot
# * finishes its movement in a desired position.
# *
# * -------------------------------------------------------------------


# -------- LOADING REQUIRED LIBRARIES --------
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import String, Bool
from camera_acquisition.msg import ImageWithPose
from camera_acquisition.srv import acquire, acquireResponse

# -------- TOPICS DECLARATION --------
topic = "/pepper_robot/camera/front/camera/image_raw" # on which acquires image stream
topic_image = "/image_capture" # on which publishes the captured images
joint_service = "check_acquisition"

# -------- CLASS DECLARATION --------
class ImageRetriever:
    """
    The ImageRetriever class is responsible to show the video captured from the camera
    """
  
    def __init__(self, topic, joint_service, topic_image):
        """ 
        This method initializes the ImageRetriever object, subscribing it to 2 topics and
        make it publisher on another one.

        Args:
            topic (String): topic name on which acquires image stream
            topic_joint (String): topic name on which acquires Pepper movement
            topic_image (String): topic name on which publishes the captured images
        """ 
        self.catch = False
        self.pose = None
        self.frame = None

        rospy.loginfo("Intializing Subcriber to topic %s", topic) 
        self.image_sub = rospy.Subscriber(topic, Image, self.callback)
        """rospy.loginfo("Intializing Subcriber to topic %s", topic_joint) 
        self.image_joint = rospy.Subscriber(topic_joint, String, self.catch_callback)"""
        rospy.loginfo("Intializing Publisher to topic %s", topic_image) 
        self.image_pub = rospy.Publisher(topic_image, ImageWithPose, queue_size=0)
        rospy.loginfo("Intializing Server of service %s", joint_service)
        self.server = rospy.Service(joint_service, acquire, self.catch_callback)
        

    def callback(self, data):
        """
        This is the callback called when robot camera publishes an image.

        Args:
            data (sensor_msgs/Image): stream of robot camera
        """
        self.frame = data

    def catch_callback(self, req):
        """
        This is the callback called when the robot has finished the movement in order to launch the catching of the image.

        Args:
            data (std_msgs/String): position of robot's head
        """    
        rospy.loginfo("Trying to catch image...")
        flag = Bool()
        if self.frame is None:
            flag.data = False
            return acquireResponse(flag)
        else:
            flag.data = True
            msg = ImageWithPose()
            msg.pose = req.pose_request
            msg.image = self.frame
            # Publish message
            self.image_pub.publish(msg)
            rospy.loginfo("Image published..")
            return acquireResponse(flag)

# -------- MAIN --------
if __name__ == '__main__':
    rospy.init_node("camera_stream")
    rospy.loginfo("Intialized /image_acquire node")
    ir = ImageRetriever(topic, joint_service, topic_image)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
