#!/usr/bin/env python
import rospy
from naoqi_driver import NaoqiNode
from animated_say.srv import say 

class AnimatedSay(NaoqiNode):
    def __init__(self):
        # Node initialization
        NaoqiNode.__init__(self, 'animated_speech')
        self.connectNaoQi()
        pass

    def say(self, data):
        rospy.loginfo("Start: %s", data.message)
        # The parameters comes from the service captured 'animated_say'
        self.speech.say(data.message)
        rospy.loginfo("End: %s", data.message)
        return SayResponse(True)

    def connectNaoQi(self):
        # Speech proxy attachment
        self.speech = self.get_proxy("ALAnimatedSpeech")
        self.srv = rospy.Service('animated_say', say, self.say)

if __name__ == "__main__":
    # Create the AnimatedSay object
    pub = AnimatedSay()
    rospy.spin()