#!/usr/bin/env python
import rospy
from naoqi_driver.naoqi_driver import NaoqiNode
from animated_say.srv import say 

class AnimatedSay(NaoqiNode):
    def __init__(self):
        NaoqiNode.__init__(self, 'animated_speech')
        self.connectNaoQi()
        pass

    def say(self, msg):
        rospy.loginfo("Start: %s", data.message)
        self.speech.say(msg)
        rospy.loginfo("End: %s", data.message)
        return SayResponse(True)

    def connectNaoQi(self):
        self.speech = self.get_proxy("ALAnimatedSpeech")

    def when_done(self):
        msg = ""
        self.say(msg)

if __name__ == "__main__":
    pub = AnimatedSay()
    rospy.spin()