#!/usr/bin/env python
# -------------------------------------------------------------------
# *
# * This module has been developed by Group 18 @ Cognitive Robotics DIEM.UNISA.
# *
# * Title:    wait_say
# * Author:   Fina, Puzo, Russomanno, Ventre
# * Org.:     UNISA - DIEM - Artificial Intelligence - Cognitive Robotics - Group 18
# * Date:     23 Nov, 2020
# *
# * This file implements a ROS node to generate a pre-established sentence
# * for Pepper to say while waiting for the loading f the images and the
# * inference on them.
# *
# * -------------------------------------------------------------------

import time
import rospy
from naoqi_driver import NaoqiNode
from collections import Counter
from pepper_detector.msg import DetectionWithPose

class TalkException(Exception):
    """
    The TalkException class extends Exception
    """
    pass

class PepperTalk(NaoqiNode):
    """
    The PepperTalk class extends NaoqiNode in order to handle with Pepper
    proxies available in the NaoQi Module
    """
    def __init__(self):
        """
        The PepperTalk class constructor
        """
        NaoqiNode.__init__(self, 'wait_say')
        self.connect_naoqi()
        # Tracks the model initialization
        self.construct_msg()
        self.talking()
        pass

    def construct_msg(self):
        """
        The construct_msg() function initializes the msgs array that Pepper has to say
        """
        # This function creates different sentences to tell during the waiting time 
        # (setup phase and loading of the model) and sets the speech speed
        self.msg = [
            "\RSPD=70\ Hi, ^start(animations/Stand/Gestures/Hey_6) let me see what I can find.",
            "\RSPD=70\ Ok, ^start(animations/Stand/BodyTalk/BodyTalk_3) now I'm going to look around a bit.",
            "\RSPD=70\ Give ^start(animations/Stand/BodyTalk/BodyTalk_22) me a minute, I'm working on it."
        ]

    def init_subs(self, topic):
        """
        The init_subs() function initialize the ROS subscriber responsible to detect poses
        
        Args:
            topic (string): the topic to which the node must be subscribed
        """
        # Init subscriber for receiving detections
        self.say_sub = rospy.Subscriber(topic, DetectionWithPose, self.callback)

    def connect_naoqi(self):
        """
        The connect_naoqi() function attaches the ALAnimatedSpeech proxy
        """
        # Speech Proxy attachment
        self.speech = self.get_proxy("ALAnimatedSpeech")

    def say(self, msg):
        """
        The say() function is responsible to use the proxy and send phrases that Pepper has to say
        
        Args:
        msg (string): the phrase that Pepper must say
        """
        # Sending phrase and bodyLanguage to Pepper
        self.speech.say(msg, {"bodyLanguageMode":"contextual"})

    def talking(self):
        """
        The talking() function makes Pepper able to talk and say something until an exception is caught or
        all the phrases are said
        """
        # Setting the three sentences with an intervall between them. 
        # Stop talking if the model is loaded.
        try:
            for i in range(len(self.msg)):
                self.say(self.msg[i])
                time.sleep(10)
        except TalkException:
            rospy.loginfo("Model loaded")
            
        
    def callback(self, data):
        """
        The callback() function is responsible to make Pepper stop talking and raise an Exception

        Raises:
        TalkException: If the Object Detection model is ready, then stop talking()
        """
        self.say_sub.unregister()
        self.say("\RSPD=70\ I think ^start(animations/Stand/Gestures/Explain_4) I saw something, I'll tell you what in a second.")
        raise TalkException("Model Ready, Stop Talking")

if __name__ == "__main__":
    pepper_say = PepperTalk()
    pepper_say.init_subs("/pepper_detective")
    rospy.spin()
