#!/usr/bin/env python3

# TO REMOVE ???

""" -------------------------------------------------------------------
 *
 * This module has been developed by Group 18 @ Cognitive Robotics DIEM.UNISA.
 *
 * Title:	visualization_node
 * Author:	Fina, Puzo, Russomanno, Ventre
 * Org.: 	UNISA - DIEM - Artificial Intelligence - Cognitive Robotics - Group 18
 * Date:    23 Nov, 2020
 *
 * This file implements a ROS node which receives detections and shows them on the image.
 * -------------------------------------------------------------------
 """

# -------- LOADING REQUIRED LIBRARIES --------
import os
import rospy
from camera_acquisition.msg import ImageWithPose
from pepper_detector.msg import DetectionWithPose
from sensor_msgs.msg import Image
from vision_msgs.msg import Detection2D, Detection2DArray, ObjectHypothesisWithPose
import cv2
import ros_numpy
from threading import Lock
from classmap import category_map as classmap

DEBUG = False

rospy.init_node('visualization_node')
image_lock = Lock()
image = None

def rcv_detection(msg):
    global image
    rospy.loginfo('detection here')
    image_lock.acquire()
    if image is None: im = None
    else: im = image.copy()
    image_lock.release()
    if im is None: return
    h,w,_ = im.shape
    for d in msg.detections:
        c = d.results[0].id
        s = d.results[0].score
        b = [d.bbox.center.y,d.bbox.center.x,d.bbox.size_y, d.bbox.size_x]
        b[0]-=b[2]/2
        b[1]-=b[3]/2
        p1 = (int(b[1]*w+.5), int(b[0]*h+.5))
        p2 = (int((b[3]+b[1])*w+.5), int((b[2]+b[0])*h+.5))
        print(classmap[c], s)
        col = (255,0,0) 
        cv2.rectangle(im, p1, p2, col, 3 )
        p1 = (p1[0]-10, p1[1])
        cv2.putText(im, "%s %.2f" % (classmap[c],s), p1, cv2.FONT_HERSHEY_SIMPLEX, 0.8, col, 2)
    cv2.imshow("Capture", im)
    cv2.waitKey(0)

def rcv_image(msg):
    global image
    rospy.loginfo('image here')
    image_lock.acquire()
    image = ros_numpy.numpify(msg.image)
    image_lock.release()

if DEBUG:
    si = rospy.Subscriber("/image_capture", ImageWithPose, rcv_image)
    sd = rospy.Subscriber("/image_boxes", DetectionWithPose, rcv_detection)

try:
    rospy.spin()

except KeyboardInterrupt:
    print("Shutting down")
    